### ISSUE TITLE
AUX HEADER

### ISSUE THREAD

**Issue by leshasoft** [michal-josef-spacek/CAD-Format-DWG-AC1009#3]
I hacked this structure
```

SIZE	    DESCRIPTION
2 bytes	    Value 16
2 bytes	    Size of aux header
4 bytes	    Entity start address
4 bytes	    Block def start address
4 bytes	    Extra ent start address
1 byte	    Value 1
1 byte	    Value 0
8 bytes	    HANDSEED variable
2 bytes	    Number of records
---------------------------------
    N records, where:
2 bytes	     Section id
2 bytes	     Size section records
2 bytes	     Number records in section
4 bytes	     Address section
----------------------------------
4 bytes	     Address aux begin sentinel
2 bytes	     CRC
16 bytes     sentinel
```

**Comment by michal-josef-spacek** [comment]
@leshasoft Interesting.

I have:
```
  aux_header:
    seq:
      - id: aux_header_sentinel_begin
        contents: [0x29, 0x8D, 0xD1, 0x49, 0xA9, 0x73, 0x1F, 0xEA, 0x99, 0xDE, 0x32, 0xF9, 0x4D, 0x0A, 0xE0, 0x19]
      - id: u2
        type: s2
      - id: u3
        type: s2
      - id: entities_start
        type: s4
      - id: entities_end
        type: s4
      - id: blocks_start
        type: s4
      - id: blocks_end
        type: s4
      - id: handling
        type: u2
      - id: handseed
        size: 8
      - id: num_aux_tables
        type: u2
      - id: aux_tables
        type: table_aux
        repeat: expr
        repeat-expr: num_aux_tables
      - id: u1_address
        type: s4
      - id: crc16
        size: 2
      - id: aux_header_sentinel_end
        contents: [0xD6, 0x72, 0x2E, 0xB6, 0x56, 0x8C, 0xE0, 0x15, 0x66, 0x21, 0xCD, 0x06, 0xB2, 0xF5, 0x1F, 0xE6]
```

You are right, that could be size and different addresses.. Thanks.
